pipeline {
    agent any

    environment {
        DIRECTORY_PATH = 'C:/Users/DELL/Desktop/sem4/sit223'
        TESTING_ENVIRONMENT = 'staging'
        PRODUCTION_ENVIRONMENT = 'Seerat'
    } 
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/seerat-00/Demo-pipeline.git'
            }
        } 
        
        stage('Build') {
            steps {
                script {
                    echo "Fetch the source code from the directory path: ${DIRECTORY_PATH}"
                    echo "Compile the code and generate any necessary artifacts"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo "Unit tests"
                    echo "Integration tests"
                }
            }
        }

        stage('Code Quality Check') {
            steps {
                script {
                    echo "Check the quality of the code"
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Deploy the application to the testing environment: ${TESTING_ENVIRONMENT}"
                }
            }
        }

        stage('Approval') {
            steps {
                script {
                    echo "Waiting for manual approval..."
                    sleep 10
                }
            }
        }

        stage('Deploy to Production') {
            steps {
                script {
                    echo "Deploying the application to the production environment: ${PRODUCTION_ENVIRONMENT}"
                }
            }
        }
    }
}
