pipeline {
    agent any

    environment {
        DIRECTORY_PATH = 'C:/Users/DELL/Desktop/sem4/sit223'
        TESTING_ENVIRONMENT = 'staging'
        PRODUCTION_ENVIRONMENT = 'Seerat'
    } 
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/seerat-00/Demo-pipeline.git'
            }
        } 
        
        stage('Build') {
            steps {
                script {
                    echo "Fetch the source code from the directory path: ${DIRECTORY_PATH}"
                    echo "Compiling the code and generating artifacts..."
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo "Running Unit Tests..."
                    echo "Running Integration Tests..."
                }
            }
        }

        stage('Code Quality Check') {
            steps {
                script {
                    echo "Checking code quality..."
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Deploying the application to the testing environment: ${TESTING_ENVIRONMENT}"
                }
            }
        }

        stage('Approval') {
            steps {
                script {
                    echo "Waiting for manual approval..."
                    sleep 10
                }
            }
        }

        stage('Deploy to Production') {
            steps {
                script {
                    echo "Deploying the application to the production environment: ${PRODUCTION_ENVIRONMENT}"
                }
            }
        }
    }

    post {
        always {
            script {
                def buildStatus = currentBuild.currentResult
                def buildUser = currentBuild.getBuildCauses().find { it.className == 'hudson.model.Cause$UserIdCause' }?.userId ?: 'GitHub User'

                emailext(
                    subject: "Pipeline ${buildStatus}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    body: """
                        <p><b>Jenkins Pipeline Build Status:</b> ${buildStatus}</p>
                        <p><b>Started by:</b> ${buildUser}</p>
                        <p>Check details in Jenkins.</p>
                    """,
                    mimeType: 'text/html',
                    to: 'iseeratsharmash@gmail.com',
                    from: 'iseeratsharmash@gmail.com',
                    replyTo: 'iseeratsharmash@gmail.com'
                )
            }
        }
    }
}
